# Teknik alan anahtar kelimeleri
DOMAIN_KEYWORDS = {
    'ml': [
        'makine öğrenmesi', 'ml', 'machine learning', 
        'yapay zeka', 'ai', 'artificial intelligence',
        'derin öğrenme', 'deep learning',
        'supervised learning', 'unsupervised learning',
        'reinforcement learning', 'pekiştirmeli öğrenme',
        'model', 'algoritma', 'algorithm',
        'eğitim', 'training', 'test', 'validation',
        'overfitting', 'underfitting', 'regularization',
        'cross validation', 'hyperparameter', 'hiperparametre',
        'xgboost', 'lightgbm', 'fitting', 'target', 'F1', 'skor',
        'accuracy', 'regresyon', 'classification', 'sınıflandırma',
        'clustering', 'kümeleme', 'regression', 'ensemble', 'cnn', 'rnn',
        'lstm', 'gan', 'bert', 'gpt', 'word2vec', 'embedding', 'tokenization',
        'feature engineering', 'özellik mühendisliği', 'feature selection', 'özellik seçimi',
        'dimensionality reduction', 'boyut indirgeme', 'pca', 'principal component analysis',
        'cross-validation', 'model evaluation', 'confusion matrix', 'precision', 'recall',
        'roc', 'auc', 'bias', 'variance', 'hyperparameter tuning', 'grid search',
        'random forest', 'decision tree', 'svm', 'naive bayes', 'k-means', 'kmeans',
        'autoML', 'transfer learning', 'active learning', 'explainable ai', 'fairness',
        'mlops', 'model deployment', 'model serving', 'monitoring', 'pipeline',
    ],
    'data_science': [
        'veri bilimi', 'data science', 
        'veri analizi', 'data analysis',
        'veri madenciliği', 'data mining',
        'istatistik', 'statistics',
        'veri ön işleme', 'data preprocessing',
        'feature engineering', 'özellik mühendisliği',
        'feature selection', 'özellik seçimi',
        'dimensionality reduction', 'boyut indirgeme',
        'pca', 'principal component analysis',
        'clustering', 'kümeleme',
        'regression', 'regresyon',
        'classification', 'sınıflandırma',
        'analiz', 'dağılım', 'varyans', 'standart sapma', 'ortalama', 'medyan', 'mod',
        'frekans', 'popülasyon', 'örneklem', 'hipotez', 'p-değeri', 'anova', 'ki-kare',
        'chi-square', 'normal dağılım', 'binom dağılım', 'poisson dağılım', 'standart hata',
        'betimsel', 'istatistiksel test', 'regresyon analizi', 'varyans analizi',
        'veri seti', 'veri temizleme', 'veri modelleme', 'veri işleme', 'veri keşfi',
        'big data', 'veri yönetimi', 'data engineering', 'etl', 'data pipeline',
        'data warehouse', 'data lake', 'data mart', 'dashboard', 'görselleştirme',
        'matplotlib', 'seaborn', 'plotly', 'tableau', 'power bi',
    ],
    'programming': [
        'programlama', 'programming',
        'kod', 'code', 'yazılım', 'software',
        'python', 'java', 'javascript', 'c++', 'c#', 'ruby', 'php',
        'veri yapıları', 'data structures',
        'algoritma', 'algorithm',
        'fonksiyon', 'function',
        'sınıf', 'class',
        'nesne', 'object',
        'değişken', 'variable',
        'döngü', 'loop',
        'koşul', 'condition',
        'if', 'else', 'for', 'while', 'try', 'except', 'import', 'print', 'input', 'return',
        'append', 'split', 'join', 'lambda', 'map', 'filter', 'global', 'local', 'sort', 'len',
        'enumerate', 'open', 'read', 'write', 'with', 'yield', 'self', 'True', 'False',
        'docker', 'flask', 'django', 'sql', 'nosql', 'git', 'github', 'gitlab', 'bitbucket',
        'branch', 'commit', 'merge', 'pull request', 'fork', 'clone', 'remote', 'origin',
        'submodule', 'virtualenv', 'pip', 'requirements', 'package', 'library', 'framework',
        'oop', 'mvc', 'rest', 'api', 'endpoint', 'json', 'xml', 'yaml', 'html', 'css',
        'frontend', 'backend', 'fullstack', 'devops', 'ci/cd', 'test', 'unit test', 'integration test',
    ],
    'security': [
        'güvenlik', 'security',
        'veri sızıntısı', 'data leakage',
        'veri gizliliği', 'data privacy',
        'şifreleme', 'encryption',
        'kimlik doğrulama', 'authentication',
        'yetkilendirme', 'authorization',
        'güvenlik açığı', 'vulnerability',
        'saldırı', 'attack',
        'korumalı', 'protected',
        'güvenli', 'secure',
        'data breach', 'penetration testing', 'cybersecurity', 'ssl', 'tls', 'oauth',
        'multi-factor authentication', 'iso 27001', 'gdpr', 'hipaa', 'data masking',
        'incident response', 'soc', 'ethical hacking', 'firewall', 'antivirus',
    ]
}
    